### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ewewo2** [sethtallen/C4RD1N4L_V2#1]
error code 2

**Comment by sethtallen** [comment]
I haven't tested on Windows, but it should be platform agnostic.

The my_utils modules should be included with your RBVC installation. You will find a my_utils.py file in the top level directory. Are you running infer_cli.py with the working directory set as your RBVC installation?

**Comment by ewewo2** [comment]
Thank you for your answer. I manually copied the utils.py into the directory. It seems that I get no error (I get some kind of confirmation message "没有发现支持的N卡, 使用CPU进行推理") but the inferenced file is not created. Any new ideas how I could get it to work?

**Comment by sethtallen** [comment]
Can you post your code, along with the contents of the directory you're running everything from?

I believe that message is saying that you're using the CPU to infer, i.e. you don't have a GPU or its not finding it. I haven't done CPU inference, but it will be very slow. Is there no other text which follows?

**Comment by ewewo2** [comment]
This is the complete file and folder list (I used the official github Windows prebuild, all dependencies are installed via pip install -r requirements and the webui is working well).
.github
.gitignore
__pycache__
app.py
config.py
configs
Dockerfile
docs
environment_dml.yaml
extract_f0_print.py
extract_feature_print.py
extract_locale.py
go-realtime-gui.bat
go-web.bat
gui_v0.py
gui_v1.py
guidml.py
i18n
i18n.py
infer_batch_rvc.py
infer_cli.py
infer_pack
infer_uvr5.py
infer-web.py
lib
LICENSE
logs
MDXNet.py
my_utils.py
myinfer.py
myinfer-v2-0528.pyx
poetry.lock
pretrained
pretrained_v2
pyproject.toml
README.md
requirements.txt
requirements-win-for-realtime_vc_gui.txt
Retrieval_based_Voice_Conversion_WebUI.ipynb
Retrieval_based_Voice_Conversion_WebUI_v2.ipynb
rmvpe.py
run.sh
rvc_for_realtime.py
slicer2.py
tools
train
train_nsf_sim_cache_sid_load_pretrain.py
trainset_preprocess_pipeline_print.py
uvr5_weights
vc_infer_pipeline.py
venv.sh
weights

This is my prompt:
python infer_cli.py 0 "C:\013.wav" "C:\added_IVF102_Flat_nprobe_1_039_voice_v1.index" harvest "test.wav" "C:\039_voice.pth" 0.6 1 cuda:0 True

And this is the message I get, no following code etc.:
没有发现支持的N卡, 使用CPU进行推理

**Comment by sethtallen** [comment]
So, I notice some issues with my script. At some point the command line arguments got removed. I've readded them.

Please look at the updated script here:
https://github.com/sethtallen/C4RD1N4L_V2/blob/master/backend/infer_cli.py

Note: You will need to set line 12 of the script to "True". I didn't really expect anyone to use this, so its a little sloppy.
`using_cli = False` -> `using_cli = True`

The following command line argument worked for me on my Ubuntu server. I think the syntax should be the same on Windows. It did use my CPU for the conversion, taking about ~3 minutes across 24 physical cores.

`python infer_cli.py [transpose_value] "input_path" "output_path" "model_path" "cpu" "crepe" "index_path"`

Let me know if it works. I've been using this more as an API, so I didn't notice the CLI features were missing.

**Comment by sethtallen** [comment]
And if you do want to use a GPU, 
`python infer_cli.py [transpose_value] "input_path" "output_path" "model_path" cuda:0" "crepe" "index_path"`

if you have multiple GPUs, the 0 could be a 1 or whatever index the GPU is.

**Comment by ewewo2** [comment]
thank you so much for the update. 

it throws back a new error:
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\infer_cli.py", line 108, in <module>
    config=Config(device,is_half)
NameError: name 'device' is not defined

I used the following prompt:
C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main>python infer_cli.py 0 "C:\013.wav" "C:\test.wav" "C:\039.pth" "cpu" "harvest" "C:\added_IVF102_Flat_nprobe_1_039_v1.index"

**Comment by sethtallen** [comment]
Did you set line 12 using_cli to equal True within the script? Otherwise it will not grab the arguments.

**Comment by ewewo2** [comment]
So sorry, totally overlooked this. I changed it and now this happens after the prompt:

没有发现支持的N卡, 使用CPU进行推理
loading pth C:\039.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System cannot find file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\updated.py", line 227, in <module>
    vc_single(sid=0,input_audio_path=input_path,f0_up_key=f0_up_key,f0_file=None,f0_method=f0_method,file_index=file_index,file_index2="",index_rate=1,filter_radius=3,resample_sr=0,rms_mix_rate=0,model_path=model_path,output_path=output_path)
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\updated.py", line 155, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] System cannot find file

**Comment by sethtallen** [comment]
I would verify that the input audio file path is correct, and that the filename is correct. If it is, maybe put it into a test directory, and try it again.

I think the top level on the C: drive has some strict permissions on Windows, so I'm not sure if it could write to that directory. Unless you're running the script as an Administrator. Might be worth doing a C:\test_folder\test.wav

**Comment by ewewo2** [comment]
That idea was pretty smart. I changed all folders to a subfolder (input and output path), double checked the path to models, input audio file and index... the same error occurs.

btw: if one file is missing (I tried it to check if that might be the reason for the error) another error pops up: FileNotFoundError: [Errno 2] No such file or directory: 'C:\subfolder\039.pth'

do you have any other idea? thank you for your very kind help!!

**Comment by sethtallen** [comment]
No problem.

I would make sure that you have hide file extensions enabled within Windows Explorer. You might have something like 
C:\013.wav.wav but you can't see it.

![image](https://github.com/sethtallen/C4RD1N4L_V2/assets/85146497/95515982-60a8-413c-8339-d3052e1c6053)

You can also try to copy all of the input files to the root directory of RBVC, where your infer_cli.py file is.

So your command would look like:
`C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main>python infer_cli.py 0 "013.wav" "test.wav" "039.pth" "cpu" "harvest" "added_IVF102_Flat_nprobe_1_039_v1.index"`

**Comment by sethtallen** [comment]
With the setting enabled:
![image](https://github.com/sethtallen/C4RD1N4L_V2/assets/85146497/30d5d1de-6319-4b45-bebd-776ca705ad6d)

With it disabled:
![image](https://github.com/sethtallen/C4RD1N4L_V2/assets/85146497/8748ebeb-d27e-4ad1-9bbf-4566c4140ef9)

**Comment by ewewo2** [comment]
thx again. hide known file extension was disabled. I copied all files to the infer-script folder and followed your steps, I even shortened the index file name. still the same as before. I even used another audio file....still no luck

the last lines of the error message refer to subprocess.py
File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System cannot find file

and main_utils.py
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] System cannot find file

May it be the something in your script refers to something in those 2 script files which may not be included in the windows version?

**Comment by sethtallen** [comment]
I was able to replicate on a new installation of RBVC on my Windows machine. Try this, it resolved it for me.

Grab the Windows release of the latest FFmpeg build for Windows `ffmpeg-master-latest-win64-gpl.zip`
https://github.com/BtbN/FFmpeg-Builds/releases

Extract 'ffmpeg.exe' within 'bin' into your RBVC folder. It proceeds to inference and produces the audio file. Let me know if that works.

I believe on my Ubuntu server I have installed FFmpeg system wide and I hadn't needed to drop in this dependency.

**Comment by ewewo2** [comment]
Dear Seth, I am really thankful for your afford to help me. The Error got fixed by your solution, then it complained about a missing hubertus_base.pt which I copied in the same direction and fixed it, but now this error happens:

Traceback (most recent call last):
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\infer_cli.py", line 227, in <module>
    vc_single(sid=0,input_audio_path=input_path,f0_up_key=f0_up_key,f0_file=None,f0_method=f0_method,file_index=file_index,file_index2="",index_rate=1,filter_radius=3,resample_sr=0,rms_mix_rate=0,model_path=model_path,output_path=output_path)
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\infer_cli.py", line 163, in vc_single
    load_hubert()
  File "C:\Users\User1\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\infer_cli.py", line 120, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by sethtallen** [comment]
That's weird, does this happen with any model or audio file you try? It almost makes me think something is corrupted.

https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory
Mentions corruption causing this.

Probably redownload and verify everything in this part of the RBVC installation.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/README.en.md#preparation-of-other-pre-models
